170930
yeony1/markupStudy pull request #1
Opened 2017-10-25 08:27 UTC by yeony1

2017-10-26 13:23 UTC, JaesunPark requested changes
일부 개선 + 수정 필요

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +  <title></title>
`title`에 문서 제목이 들어가있지 않습니다.

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +    <h1 class="mainTit">평점&리뷰</h1>
평점 & 리뷰에 `&amp;`가 누락되었습니다.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .img+.review {width:calc(100% - 84px);}
calc 함수를 안쓰는 방식으로도
좌측 이미지 영역을 제거하고 우측 영역이 100%가 되게끔
구현이 가능합니다.

다른 방식으로 구현을 해보는걸 권장합니다.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .review {float:left; width:100%;}
`float: left` 속성은 불필요한 속성이라고 생각되네요.

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +    <a href="#this" class="linkBox">
`a.linkBox` 제거해주세요.

킹스맨 제목 아래는 사용자의 평점에 대한 리뷰 리스트 영역이라 개별적인 링크가 필요하기 때문입니다.

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +            <span class="star"><span class="pointStar" style="width:90%"></span></span>
`span.pointStar`에 style로 가로값을 지정해주는건 좋은 판단입니다.

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +            <span class="star"><span class="pointStar" style="width:90%"></span></span>
`span.star > span.pointStar`에서 이 영역이 어떤걸 의미하는지에 대한 텍스트 정보가 없습니다.

접근성 부분에 있어 텍스트를 제공하여야 합니다.

2017-10-26 13:23 UTC, JaesunPark commented on markup1.html
> +        <p class="txt">
`p.txt` 리스트 형식으로 마크업 수정이 필요합니다.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .review .subTit .pointBox .pointTxt {
`line-height` 속성 오타입니다.

수정해주세요.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +  position:relative; float:left; display:block; width:73px; height:13px; margin-top:3px;
`span.star`에 float 속성이 들어가있으므로 `display: block;`이 지금 당장 필요하지 않다고 생각되네요.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +  position:relative; float:left; display:block; width:73px; height:13px; margin-top:3px;
`span.star` 여백의 경우에는 외부 여백인 `margin` 보다는 내부 여백인 `padding` 속성을 사용하는걸 권장합니다.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +* {box-sizing:border-box;}
`* {box-sizing: border-box;}` 속성 해제 : 전체 선택자에 box-sizing 속성을 넣을 경우 추후 유지보수 및 타 작업자에게 혼란을 줄 수 있습니다.

2017-10-26 13:23 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .img img {width:100%; height: auto;}
이미지의 높이값은 이미지의 가로값을 따라가기 때문에
`height: auto` 속성은 불필요합니다.

2017-10-27 03:49 UTC, yeony1 commented on css/style.css
> +* {box-sizing:border-box;}
회사 컨벤션에 따라서 전체 선택자에 box-sizing을 추가해서 작업하고 있습니다.
때문에 유지보수와 타 작업자의 혼란은 방지할수 있으나 궁금한 것은, 전체 선택자로 작성했을때 브라우저 성능이나 다른면에서 문제가 발생될 수 있는지 궁금합니다.

2017-10-27 03:50 UTC, yeony1 commented on css/style.css
> +.reviewBox .linkBox .img img {width:100%; height: auto;}
가로값을 100%로 주면 세로값이 자동으로 auto로 들어가는 것은 알고있습니다. 정확한 표현을 하고싶어서 height:auto를 넣어주었는데, css파일의 용량만 더 차지하고 불필요한 속성인가요?

2017-10-27 03:58 UTC, yeony1 commented on css/style.css
> +.reviewBox .linkBox .review {float:left; width:100%;}
37, 39라인 둘다를 말씀하시는 건가요?

2017-10-27 04:02 UTC, yeony1 commented on css/style.css
> +  position:relative; float:left; display:block; width:73px; height:13px; margin-top:3px;
수정하였습니다.

2017-10-27 04:06 UTC, yeony1 commented on css/style.css
> +  position:relative; float:left; display:block; width:73px; height:13px; margin-top:3px;
span.star부분에 background가 깔려있어 padding으로 주게되면 불필요한 이미지까지 보이게 됩니다. 다른방법이 있을까요?

2017-10-27 04:06 UTC, yeony1 commented on css/style.css
> +.reviewBox .linkBox .review .subTit .pointBox .pointTxt {
수정하였습니다.

2017-10-27 04:06 UTC, yeony1 commented on markup1.html
> +  <title></title>
추가하였습니다.

2017-10-27 04:07 UTC, yeony1 commented on markup1.html
> +    <h1 class="mainTit">평점&리뷰</h1>
추가수정하였습니다.

2017-10-27 04:09 UTC, yeony1 commented on markup1.html
> +    <a href="#this" class="linkBox">
이미지, 제목, 사용자의 평점을 모두 포함한 링크가 아니라
사용자의 평점만 링크되는 것인가요?

2017-10-27 04:09 UTC, yeony1 commented on markup1.html
> +            <span class="star"><span class="pointStar" style="width:90%"></span></span>
감사합니다.

2017-10-27 04:17 UTC, yeony1 commented on markup1.html
> +            <span class="star"><span class="pointStar" style="width:90%"></span></span>
추가수정했습니다.

2017-10-27 04:19 UTC, yeony1 commented on markup1.html
> +        <p class="txt">
사용자 평점의 내용이라 문단을 의미하는 p태그를 사용하였습니다.

2017-10-27 04:38 UTC, yeony1 commented on css/style.css
> +.reviewBox .linkBox .img+.review {width:calc(100% - 84px);}
다른방식으로 수정하였습니다.
혹시 웹에서 ie하위브라우저를 고려안해도 되는 상황이나 모바일에서라면 calc를 많이 사용하시나요?

2017-10-27 09:01 UTC, JaesunPark commented on css/style.css
> +* {box-sizing:border-box;}
@yeony1 CSS가 성능에 미치는 부분은 극히 미비합니다. 거의 없다고 볼 수도 있습니다.
컨벤션으로 정해져있다면 유지보수에 대한 이슈는 없을 것이고,
추후 작업자가 추가 될 경우에도 이 부분에 대한 설명을 해준다면 별다른 이슈는 없을 것입니다.

2017-10-27 09:03 UTC, JaesunPark commented on markup1.html
> +        <p class="txt">
킹스맨 마크업의 캡쳐 원본 페이지인
http://movie.naver.com/ 에서는
사용자 평점 부분을 클릭하면 링크가 이동하게끔 되어있습니다.

2017-10-27 09:04 UTC, JaesunPark commented on markup1.html
> +    <a href="#this" class="linkBox">
@yeony1 링크가 들어가는 부분은
 - 좌측 썸네일 이미지
 - 상단 영화 제목
 - 하단 사용자 평점
입니다.

2017-10-27 09:08 UTC, JaesunPark commented on css/style.css
> +  position:relative; float:left; display:block; width:73px; height:13px; margin-top:3px;
@yeony1 아 그러네요.

이런 경우에는 `div.pointBox`에 padding 값을 줄 수도 있긴 한데요.
`em.pointTxt`에 영향을 끼칠 수 있으니,
`span.star`에 margin 값을 줘도 상관 없겠네요.

2017-10-27 09:14 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .img+.review {width:calc(100% - 84px);}
@yeony1 포털에서는 쓰는일이 거의 없다고 봐도 될 것 같고요.
calc 함수의 가장 큰 문제점은 호환성입니다.
IE의 경우 9부터 지원하며,
Android 디바이스의 경우에도 4.x 버전에서 지원을 하지 않는 경우도 있어요.

최신 디바이스 기준으로만 지원하는 모바일 프로젝트인 경우에는 calc 함수를 사용하여도 크게 상관은 없습니다.

2017-10-27 09:23 UTC, JaesunPark commented on css/style.css
> +.reviewBox .linkBox .img img {width:100%; height: auto;}
@yeony1 CSS의 용량은 크게 의미 없고요.
정확한 표현을 위해 `height: auto;` 속성이 있어야 하는것인지에 대해서는 의문이네요.

2017-11-11 01:34 UTC, JaesunPark approved these changes

2017-11-11 01:36 UTC, merged